server:
  port : 8080

api-auth-proxy:
  host: 'localhost:${server.port}'

  forward-signing:
    enabled: true
    authorization:
      baseUrl: https://oauth-server.host
      clientId: client-xyz
      clientSecret: sdfsjfdo78aesda22xx78AEDfsjfd

  resource-protection:
    enabled: true
    baseUrl: http://localhost:8080
    paths:
      - path: /v1/some-resource
        roles:
          - role-a
          - role-b
        groups:
          - group-1
          - group-2
